### ISSUE TITLE
webdav目前仅支持Basic编码登录

### ISSUE THREAD

**Issue by 77160860** [GhostenEditor/Ghosten-Player#2]
这个是要给密码转换成basic编码吗？

**Comment by GhostenEditor** [comment]
不用，登录的时候会自动转。可以参考这个[https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic)

**Comment by 77160860** [comment]
登录输入密码后不会自动跳转 目前只实现了阿里云登录  但是刮削失败

**Comment by 77160860** [comment]
视频不能全屏是指没有缩放功能

**Comment by GhostenEditor** [comment]
> 视频不能全屏是指没有缩放功能

目前没做缩放功能

**Comment by 77160860** [comment]
目前alist挂载的webdav还是无法查看内容
![IMG_2206](https://github.com/user-attachments/assets/98fb44a0-66ee-426e-98e9-5827d04945cd)
![IMG_2207](https://github.com/user-attachments/assets/59f9b7da-95e6-43de-8ea5-93c6ce3ea93e)

**Comment by GhostenEditor** [comment]
根据[alist](https://alist.nn.ci/zh/guide/webdav.html#webdav-配置)的文档，需要加路径/dav。你的配置也就是http://192.168.1.6:5244/dav

**Comment by 77160860** [comment]
http://192.168.1.6:5244/dav  用了这个查看提示错误请求！
![Uploading 1.png…]()

**Comment by GhostenEditor** [comment]
你的alist是什么版本，用的什么网盘，我测试一下

**Comment by 77160860** [comment]
用的这个alist v7a版  https://github.com/jing332/AListFlutter/releases
ios 的最新版alist也试过了

**Comment by 77160860** [comment]
刚安装1.02可以正常打开alist的webdav文件了
但是电影和电视剧目录不能使用同一个？需要挂载2个目录，如果能使用同一个目录自动匹配电视剧和电影就好了
播放hevc提示不支持  有字幕没画面

**Comment by GhostenEditor** [comment]
- 建议电影和电视剧分开放，因为两者目录的遍历和刮削逻辑是不一样的，如果后面想到了好的方案再考虑解除这个限制。
- 刮削是调用的api.themoviedb.org的接口，你可以在同一个网络下ping一下api.themoviedb.org，如果是通的就应该没问题，如果不通则有可能是dns污染导致的，你可以去搜索一些dns在线解析，找到一个可用的ip地址，按照[readme](https://github.com/GhostenEditor/Ghosten-Player?tab=readme-ov-file#dns)填上应该就可以了。
- hevc不支持可以参考[readme](https://github.com/GhostenEditor/Ghosten-Player?tab=readme-ov-file#%E7%94%BB%E9%9D%A2%E6%88%96%E5%A3%B0%E9%9F%B3%E7%BC%BA%E5%A4%B1)。如果你确定你的设备是支持hevc硬解码，请单独提一个issue
